language: android
jdk: 
  - oraclejdk8

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
 - chmod +x gradlew
 
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

android:
  components:
        - tools # to get the new `repository-11.xml`
        - tools # to install Android SDK tools 25.1.x (x = 6 right now)
        - build-tools-24.0.1
        - android-24
        - platform-tools
        - extra-android-support
        - extra-android-m2repository
        - extra-google-m2repository
        - extra-google-google_play_services

script: ./gradlew build connectedCheck
